In [2]:
import numpy as np

In [3]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print X

[[ -0.16036636 -16.87583932   8.63338208 ...,   6.43768035  10.60696404
    5.27455125]
 [  2.48333051  -6.92511311  -7.85378384 ...,  -4.00088906  -2.43678542
   -2.40374609]
 [  1.71114158 -11.09035497   3.67298589 ...,  -6.78861916   7.92753171
   -6.28502574]
 ..., 
 [-10.25926057  20.32755192   5.32566032 ...,   0.89753785   5.1475552
   -4.76175832]
 [  4.63738687  -8.71356815  -4.91015308 ...,  -4.6807141  -10.9628004
   15.60227578]
 [ 20.54058444  16.12031209  25.08170465 ...,  -8.9057894   -9.16096907
  -13.81695878]]


In [4]:
m=np.mean(X, axis=0)

In [5]:
std=np.std(X, axis=0)

In [6]:
X_norm= ((X-m)/std)

In [7]:
print X_norm

[[-0.1030058  -1.83185665  0.75739016 ...,  0.59165368  0.99352962
   0.43837887]
 [ 0.15478426 -0.82493942 -0.90799728 ..., -0.44691136 -0.36099036
  -0.34869179]
 [ 0.07948719 -1.2464216   0.25633488 ..., -0.72427112  0.71528565
  -0.74654579]
 ..., 
 [-1.0877611   1.93276667  0.42327341 ...,  0.04044804  0.42660073
  -0.59040192]
 [ 0.36482888 -1.00591377 -0.61065778 ..., -0.51454922 -1.24636903
   1.4970314 ]
 [ 1.91556878  1.50703469  2.41885398 ..., -0.93491483 -1.05925899
  -1.51861324]]


In [8]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [9]:
r = np.sum(Z, axis=1)

In [10]:
print np.nonzero(r > 10)

(array([1, 4, 5]),)


In [11]:
print r

[ 9 13  7  9 27 12]


In [13]:
A=np.eye(3)
B=np.eye(3)
AB=np.vstack((A,B))
print AB

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
